language: nix

sudo: true

git:
  depth: 1

install:
  - git clone --depth=1 https://github.com/$TRAVIS_REPO_SLUG.git bindings-DSL
  - cd bindings-DSL
  - git checkout -qf $TRAVIS_COMMIT

env:
  global:
  matrix:
    - GHCVERSION=ghc802
    - GHCVERSION=ghc822
    - GHCVERSION=ghc842

matrix:
  allow_failures:
  exclude:

script:
  - nix-build --argstr compiler $GHCVERSION
  - (cd bindings-posix ; nix-build --argstr compiler $GHCVERSION)
  - (cd bindings-gpgme ; nix-build --argstr compiler $GHCVERSION)

branches:
  only:
    - master
